# Generated by Django 3.2 on 2021-08-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isDigital', models.BooleanField(choices=[(False, 'Analógico - PWM'), (True, 'Digital')], default=True)),
                ('local', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gardens_api.local')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datatime')),
                ('valueSensor', models.FloatField(verbose_name='value')),
                ('sensorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens_api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isDigital', models.BooleanField(choices=[(False, 'Analógico - PWM'), (True, 'Digital')], default=True)),
                ('local', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gardens_api.local')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
