# Generated by Django 3.2 on 2021-08-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome', 'tipo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ano', models.IntegerField(blank=True, default=2020)),
            ],
            options={
                'ordering': ['nome', 'ano'],
            },
        ),
        migrations.CreateModel(
            name='TipoAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Objetiva'), (1, 'Discusiva'), (2, 'Somatória')], default=0)),
                ('disciplina', models.PositiveSmallIntegerField(choices=[(0, 'Física')], default=0)),
                ('editado', models.BooleanField(default=False, verbose_name='A questão já foi corrigida.')),
                ('dificuldade', models.PositiveSmallIntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10')], default=5)),
                ('enunciado', models.TextField(blank=True)),
                ('figura', models.ImageField(blank=True, upload_to='figures/')),
                ('pergunta', models.TextField(blank=True)),
                ('dados', models.CharField(blank=True, max_length=200)),
                ('resolucao', models.TextField(blank=True)),
                ('nr_utilizacoes', models.IntegerField(default=0)),
                ('data_inc', models.DateTimeField(auto_now_add=True, verbose_name='data_inc')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='data_mod')),
                ('texto_t', models.TextField(blank=True)),
                ('questao_t', models.TextField(blank=True)),
                ('resolucao_t', models.TextField(blank=True)),
                ('texto_fig', models.ImageField(blank=True, upload_to='figures/tratamento')),
                ('questao_fig', models.ImageField(blank=True, upload_to='figures/tratamento')),
                ('resolucao_fig', models.ImageField(blank=True, upload_to='figures/tratamento')),
                ('assunto_princ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_api.assunto')),
                ('fonte', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exams_api.fonte')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['data_inc'],
            },
        ),
        migrations.AddField(
            model_name='assunto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_api.tipoassunto'),
        ),
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('gabarito', models.BooleanField(default=False, verbose_name='Resposta certa')),
                ('ordem', models.PositiveSmallIntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10')], default=5, unique=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_api.questao')),
            ],
            options={
                'verbose_name_plural': 'Alternativas',
            },
        ),
    ]
