# Generated by Django 3.2 on 2021-12-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.PositiveSmallIntegerField(default=0)),
                ('isCorrect', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['orderNumber'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.PositiveSmallIntegerField(choices=[(0, 'Objetiva'), (1, 'Discusiva'), (2, 'Somatória')], default=0)),
                ('course', models.PositiveSmallIntegerField(choices=[(0, 'Física')], default=0)),
                ('isEdited', models.BooleanField(default=False, verbose_name='A questão já foi corrigida.')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10')], default=5)),
                ('enunciation', models.TextField(blank=True)),
                ('fig', models.ImageField(blank=True, upload_to='fig/')),
                ('query', models.TextField(blank=True)),
                ('additionalData', models.CharField(blank=True, max_length=200)),
                ('resolution', models.TextField(blank=True)),
                ('incTimeStamp', models.DateTimeField(auto_now_add=True, verbose_name='data_inc')),
                ('modificationTimeStamp', models.DateTimeField(auto_now=True, verbose_name='data_mod')),
                ('importText', models.TextField(blank=True)),
                ('importQuery', models.TextField(blank=True)),
                ('importResolution', models.TextField(blank=True)),
                ('importTextFig', models.ImageField(blank=True, upload_to='fig/import')),
                ('importQueryFig', models.ImageField(blank=True, upload_to='fig/import')),
                ('importResolutionFig', models.ImageField(blank=True, upload_to='fig/import')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['incTimeStamp'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField(blank=True, default=2020)),
            ],
            options={
                'ordering': ['name', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topicType', models.PositiveSmallIntegerField(choices=[(0, 'Secundário'), (1, 'Primário')], default=0)),
            ],
            options={
                'ordering': ['name', 'topicType'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='assunto_princ',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='assuntos_sec',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='fonte',
        ),
        migrations.DeleteModel(
            name='Alternativas',
        ),
        migrations.DeleteModel(
            name='Assunto',
        ),
        migrations.DeleteModel(
            name='Fonte',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
        migrations.DeleteModel(
            name='TipoAssunto',
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams_api.source'),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(to='exams_api.Topic'),
        ),
        migrations.AddField(
            model_name='alternatives',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams_api.question'),
        ),
    ]
